- hosts: all
  become: yes
  tasks:
    - name: required package install
      apt:
        name: python3-docker
    - name: Inspect multiple images
      docker_image_info:
        name: ubuntu:18.04
      register: result
      check_mode: no

    - when: not result.images or force is true
      vars:
        force: True
      import_tasks: transfer_docker_image.yml
